"""phase_8_confidence_columns

Revision ID: 1c438df3c2eb
Revises: 4b715206d767
Create Date: 2026-04-20 19:02:07.807652+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1c438df3c2eb'
down_revision: str | None = '4b715206d767'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('headcount_estimate_monthly', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('confidence_components_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('headcount_estimate_monthly', schema=None) as batch_op:
        batch_op.drop_column('confidence_components_json')
        batch_op.drop_column('confidence_score')

    # ### end Alembic commands ###
