"""phase_1_initial_schema

Revision ID: 1f3e410c2a2f
Revises: 
Create Date: 2026-04-20 17:08:15.592230+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1f3e410c2a2f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('actor_type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=256), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=128), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('canonical_domain', sa.String(length=255), nullable=True),
    sa.Column('linkedin_company_url', sa.String(length=1024), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('state_or_region', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('active', 'merged', 'defunct', 'unknown', name='company_status'), nullable=False),
    sa.Column('priority_tier', sa.Enum('P0', 'P1', 'P2', name='priority_tier'), nullable=False),
    sa.Column('status_reason', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index('ix_company_canonical_domain', ['canonical_domain'], unique=False)
        batch_op.create_index('ix_company_canonical_name', ['canonical_name'], unique=False)

    op.create_table('person',
    sa.Column('source_name', sa.Enum('manual', 'company_web', 'linkedin_public', 'sec', 'wikidata', 'free_api', 'benchmark', name='source_name_person'), nullable=False),
    sa.Column('source_person_key', sa.String(length=512), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=True),
    sa.Column('profile_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'source_person_key', name='uq_person_source_key')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_index('ix_person_source_key', ['source_person_key'], unique=False)

    op.create_table('run',
    sa.Column('kind', sa.Enum('full', 'refresh', 'company', name='run_kind'), nullable=False),
    sa.Column('status', sa.Enum('started', 'running', 'succeeded', 'failed', 'partial', 'cancelled', name='run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cutoff_month', sa.Date(), nullable=False),
    sa.Column('method_version', sa.String(length=64), nullable=False),
    sa.Column('anchor_policy_version', sa.String(length=64), nullable=False),
    sa.Column('coverage_curve_version', sa.String(length=64), nullable=False),
    sa.Column('config_hash', sa.String(length=128), nullable=False),
    sa.Column('priority_tier', sa.Enum('P0', 'P1', 'P2', name='run_priority_tier'), nullable=True),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_observation',
    sa.Column('source_name', sa.Enum('manual', 'company_web', 'linkedin_public', 'sec', 'wikidata', 'free_api', 'benchmark', name='source_name_obs'), nullable=False),
    sa.Column('entity_type', sa.Enum('company', 'person_profile', 'press_release', 'manual', 'benchmark', name='source_entity_type'), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('raw_html_path', sa.String(length=1024), nullable=True),
    sa.Column('raw_content_hash', sa.String(length=128), nullable=False),
    sa.Column('parser_version', sa.String(length=128), nullable=False),
    sa.Column('parse_status', sa.Enum('ok', 'failed', 'partial', 'gated', name='parse_status'), nullable=False),
    sa.Column('normalized_payload_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_observation', schema=None) as batch_op:
        batch_op.create_index('ix_source_observation_observed_at', ['observed_at'], unique=False)
        batch_op.create_index('ix_source_observation_source_hash', ['source_name', 'raw_content_hash'], unique=False)

    op.create_table('company_alias',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('alias_name', sa.String(length=512), nullable=False),
    sa.Column('alias_type', sa.Enum('legal', 'dba', 'old_name', 'acquired_by', 'subsidiary', 'brand', name='alias_type'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_alias', schema=None) as batch_op:
        batch_op.create_index('ix_company_alias_name', ['alias_name'], unique=False)

    op.create_table('company_anchor_observation',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('source_observation_id', sa.String(), nullable=True),
    sa.Column('anchor_type', sa.Enum('current_headcount_anchor', 'historical_statement', 'manual_anchor', 'reconciled_anchor', name='anchor_type'), nullable=False),
    sa.Column('headcount_value_min', sa.Float(), nullable=False),
    sa.Column('headcount_value_point', sa.Float(), nullable=False),
    sa.Column('headcount_value_max', sa.Float(), nullable=False),
    sa.Column('headcount_value_kind', sa.Enum('exact', 'range', 'bucket', name='headcount_value_kind'), nullable=False),
    sa.Column('anchor_month', sa.Date(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('headcount_value_min <= headcount_value_point AND headcount_value_point <= headcount_value_max', name='ck_company_anchor_interval_monotonic'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_observation_id'], ['source_observation.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_anchor_observation', schema=None) as batch_op:
        batch_op.create_index('ix_company_anchor_company_month', ['company_id', 'anchor_month'], unique=False)

    op.create_table('company_candidate',
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('source_workbook', sa.String(length=512), nullable=False),
    sa.Column('source_sheet', sa.String(length=128), nullable=False),
    sa.Column('source_row_index', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=512), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending_resolution', 'resolved', 'failed', name='candidate_status'), nullable=False),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_workbook', 'source_sheet', 'source_row_index', name='uq_company_candidate_source_row')
    )
    op.create_table('company_event',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.Enum('acquisition', 'merger', 'rebrand', 'spinout', 'layoff', 'parent_sub_reassignment', 'stealth_to_public', name='event_type'), nullable=False),
    sa.Column('event_month', sa.Date(), nullable=False),
    sa.Column('source_observation_id', sa.String(), nullable=True),
    sa.Column('source_class', sa.Enum('first_party', 'benchmark', 'press', 'manual_hint', 'manual', name='event_source_class'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_observation_id'], ['source_observation.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_event', schema=None) as batch_op:
        batch_op.create_index('ix_company_event_company_month_type', ['company_id', 'event_month', 'event_type'], unique=False)

    op.create_table('company_relation',
    sa.Column('parent_id', sa.String(), nullable=False),
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('acquired', 'renamed', 'spinout', 'subsidiary', 'brand', name='relation_kind'), nullable=False),
    sa.Column('effective_month', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_observation_id', sa.String(), nullable=True),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_observation_id'], ['source_observation.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_run_status',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('stage', sa.Enum('canonicalize', 'collect_anchors', 'collect_employment', 'estimate_series', 'score_confidence', 'export', name='company_run_stage'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'gated', 'review', name='company_run_stage_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=2048), nullable=True),
    sa.Column('last_progress_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'company_id', 'stage', name='uq_company_run_stage')
    )
    op.create_table('company_source_link',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('source_name', sa.Enum('manual', 'company_web', 'linkedin_public', 'sec', 'wikidata', 'free_api', 'benchmark', name='source_name'), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('source_external_id', sa.String(length=512), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimate_version',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('estimation_run_id', sa.String(), nullable=False),
    sa.Column('method_version', sa.String(length=64), nullable=False),
    sa.Column('anchor_policy_version', sa.String(length=64), nullable=False),
    sa.Column('coverage_curve_version', sa.String(length=64), nullable=False),
    sa.Column('source_snapshot_cutoff', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'superseded', name='estimate_version_status'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estimation_run_id'], ['run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_override',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('field_name', sa.Enum('canonical_company', 'current_anchor', 'event_segment', 'estimate_suppress_window', 'company_relation', 'person_identity_merge', name='override_field'), nullable=False),
    sa.Column('override_value_json', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=2048), nullable=True),
    sa.Column('entered_by', sa.String(length=256), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_employment_observation',
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('source_observation_id', sa.String(), nullable=True),
    sa.Column('observed_company_name', sa.String(length=512), nullable=True),
    sa.Column('job_title', sa.String(length=512), nullable=True),
    sa.Column('start_month', sa.Date(), nullable=False),
    sa.Column('end_month', sa.Date(), nullable=True),
    sa.Column('is_current_role', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_month IS NULL OR end_month >= start_month', name='ck_employment_end_after_start'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_observation_id'], ['source_observation.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_employment_observation', schema=None) as batch_op:
        batch_op.create_index('ix_employment_company_start', ['company_id', 'start_month'], unique=False)
        batch_op.create_index('ix_employment_person', ['person_id'], unique=False)

    op.create_table('person_identity_merge',
    sa.Column('primary_person_id', sa.String(), nullable=False),
    sa.Column('duplicate_person_id', sa.String(), nullable=False),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.Column('entered_by', sa.String(length=256), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('primary_person_id <> duplicate_person_id', name='ck_person_identity_merge_distinct'),
    sa.ForeignKeyConstraint(['duplicate_person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_budget',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('source_name', sa.Enum('manual', 'company_web', 'linkedin_public', 'sec', 'wikidata', 'free_api', 'benchmark', name='source_name_budget'), nullable=False),
    sa.Column('requests_used', sa.Integer(), nullable=False),
    sa.Column('requests_allowed', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'tripped', 'exhausted', name='source_budget_status'), nullable=False),
    sa.Column('tripped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trip_reason', sa.String(length=256), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'source_name', name='uq_source_budget_run_source')
    )
    op.create_table('anchor_reconciliation',
    sa.Column('estimate_version_id', sa.String(), nullable=False),
    sa.Column('chosen_point', sa.Float(), nullable=False),
    sa.Column('chosen_min', sa.Float(), nullable=False),
    sa.Column('chosen_max', sa.Float(), nullable=False),
    sa.Column('inputs_json', sa.JSON(), nullable=False),
    sa.Column('weights_json', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['estimate_version_id'], ['estimate_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('confidence_component_score',
    sa.Column('estimate_version_id', sa.String(), nullable=False),
    sa.Column('component_name', sa.String(length=128), nullable=False),
    sa.Column('component_score', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['estimate_version_id'], ['estimate_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('headcount_estimate_monthly',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('estimate_version_id', sa.String(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('estimated_headcount', sa.Float(), nullable=False),
    sa.Column('estimated_headcount_min', sa.Float(), nullable=False),
    sa.Column('estimated_headcount_max', sa.Float(), nullable=False),
    sa.Column('public_profile_count', sa.Integer(), nullable=False),
    sa.Column('scaled_from_anchor_value', sa.Float(), nullable=False),
    sa.Column('method', sa.Enum('scaled_ratio', 'scaled_ratio_coverage_corrected', 'degraded_current_only', 'suppressed_low_sample', name='estimate_method'), nullable=False),
    sa.Column('confidence_band', sa.Enum('high', 'medium', 'low', 'manual_review_required', name='confidence_band'), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('suppression_reason', sa.String(length=256), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('estimated_headcount_min <= estimated_headcount AND estimated_headcount <= estimated_headcount_max', name='ck_headcount_estimate_interval_monotonic'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estimate_version_id'], ['estimate_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estimate_version_id', 'month', name='uq_headcount_estimate_version_month')
    )
    with op.batch_alter_table('headcount_estimate_monthly', schema=None) as batch_op:
        batch_op.create_index('ix_headcount_estimate_company_month_version', ['company_id', 'month', 'estimate_version_id'], unique=False)

    op.create_table('review_queue_item',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('estimate_version_id', sa.String(), nullable=True),
    sa.Column('review_reason', sa.Enum('low_confidence', 'resolution_ambiguity', 'linkedin_gated', 'benchmark_disagreement', 'degraded_run', 'anomaly', 'anchor_disagreement', 'manual', name='review_reason'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'assigned', 'resolved', 'dismissed', name='review_status'), nullable=False),
    sa.Column('assigned_to', sa.String(length=256), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estimate_version_id'], ['estimate_version.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_queue_item')
    with op.batch_alter_table('headcount_estimate_monthly', schema=None) as batch_op:
        batch_op.drop_index('ix_headcount_estimate_company_month_version')

    op.drop_table('headcount_estimate_monthly')
    op.drop_table('confidence_component_score')
    op.drop_table('anchor_reconciliation')
    op.drop_table('source_budget')
    op.drop_table('person_identity_merge')
    with op.batch_alter_table('person_employment_observation', schema=None) as batch_op:
        batch_op.drop_index('ix_employment_person')
        batch_op.drop_index('ix_employment_company_start')

    op.drop_table('person_employment_observation')
    op.drop_table('manual_override')
    op.drop_table('estimate_version')
    op.drop_table('company_source_link')
    op.drop_table('company_run_status')
    op.drop_table('company_relation')
    with op.batch_alter_table('company_event', schema=None) as batch_op:
        batch_op.drop_index('ix_company_event_company_month_type')

    op.drop_table('company_event')
    op.drop_table('company_candidate')
    with op.batch_alter_table('company_anchor_observation', schema=None) as batch_op:
        batch_op.drop_index('ix_company_anchor_company_month')

    op.drop_table('company_anchor_observation')
    with op.batch_alter_table('company_alias', schema=None) as batch_op:
        batch_op.drop_index('ix_company_alias_name')

    op.drop_table('company_alias')
    with op.batch_alter_table('source_observation', schema=None) as batch_op:
        batch_op.drop_index('ix_source_observation_source_hash')
        batch_op.drop_index('ix_source_observation_observed_at')

    op.drop_table('source_observation')
    op.drop_table('run')
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index('ix_person_source_key')

    op.drop_table('person')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index('ix_company_canonical_name')
        batch_op.drop_index('ix_company_canonical_domain')

    op.drop_table('company')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
